### ISSUE TITLE
On click of the link on readme the url should open on next tab.

### ISSUE THREAD

**Issue by bhumika-1-3** [origranot/url-shortener#109]

**Comment by origranot** [comment]
Do you mean on the click on live demo?

**Comment by bhumika-1-3** [comment]
Yes . Can you assign it to me ?

**Comment by IncredibleZuess** [comment]
Hi! I took a shot at the issue here.

This issue seems like it is impossible using Github because of how kramdown(Github's markdown engine) is configured

Github does not allow markdown to open to a new tab because of possible exploits and performance issues which use the `target="_blank"` attribute.

Where an easy fix would have been adding this to the `Readme.md`:
```js
<a href="https://url-shortener-live.herokuapp.com" target="_blank" rel="noreferrer noopener">View Demo</a>
```
But Github just renders them as:
```js
<a href="https://url-shortener-live.herokuapp.com" rel="noopener">View Demo</a>
```

Here is the issue for further reading :)
https://github.com/mojombo/github-flavored-markdown/issues/28

**Comment by origranot** [comment]
> Hi! I took a shot at the issue here.
> 
> This issue seems like it is impossible using Github because of how kramdown(Github's markdown engine) is configured
> 
> Github does not allow markdown to open to a new tab because of possible exploits and performance issues which use the `target="_blank"` attribute.
> 
> Where an easy fix would have been adding this to the `Readme.md`:
> 
> ```js
> <a href="https://url-shortener-live.herokuapp.com" target="_blank" rel="noreferrer noopener">View Demo</a>
> ```
> 
> But Github just renders them as:
> 
> ```js
> <a href="https://url-shortener-live.herokuapp.com" rel="noopener">View Demo</a>
> ```
> 
> Here is the issue for further reading :) [mojombo/github-flavored-markdown#28](https://github.com/mojombo/github-flavored-markdown/issues/28)

Thank you so much!
Looks like we can't implement this..
